p8105\_hw3\_qg2155
================
Qiu Xia (Helen) Guan
10/11/2018

``` r
library(tidyverse)
```

    ## ── Attaching packages ────────────────────────────────────────── tidyverse 1.2.1 ──

    ## ✔ ggplot2 3.0.0     ✔ purrr   0.2.5
    ## ✔ tibble  1.4.2     ✔ dplyr   0.7.6
    ## ✔ tidyr   0.8.1     ✔ stringr 1.3.1
    ## ✔ readr   1.1.1     ✔ forcats 0.3.0

    ## ── Conflicts ───────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
library(patchwork)
library(p8105.datasets)
```

``` r
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = 1.3,
  out.width = "90%"
)

theme_set(theme_bw() + theme(legend.position = "bottom"))
```

Problem 1
---------

### Load and clean BRFSS dataset

``` r
data("brfss_smart2010")
```

``` r
brfss_data = brfss_smart2010 %>% 
  janitor::clean_names() %>% 
  filter(topic == "Overall Health") %>% 
  mutate(response = factor(response))
```

### Summarizing distinct locations

``` r
brfss_data %>% 
  filter(year == 2002) %>% 
  group_by(locationabbr) %>%
  summarize(n_locations = n_distinct(locationdesc))
```

    ## # A tibble: 49 x 2
    ##    locationabbr n_locations
    ##    <chr>              <int>
    ##  1 AK                     1
    ##  2 AL                     1
    ##  3 AR                     1
    ##  4 AZ                     2
    ##  5 CA                     1
    ##  6 CO                     4
    ##  7 CT                     7
    ##  8 DC                     1
    ##  9 DE                     3
    ## 10 FL                     7
    ## # ... with 39 more rows

In 2002, there were 3 states that were observed at 7 locations. These 3 states were CT, FL, and NC.

### Creating spaghetti plot of number locations

``` r
brfss_data %>% 
  group_by(locationabbr, year) %>%
  summarize(n_locations = n_distinct(locationdesc)) %>% 
  ggplot(aes(x = year, y = n_locations, color = locationabbr)) + 
    geom_point() + geom_line()
```

<img src="p8105_hw3_qg2155_files/figure-markdown_github/spaghetti plot-1.png" width="90%" />

This spaghetti plot shows the number of locations in each state from 2002 to 2010. Florida in particular seems to have over 40 distinct loactions in two different time points.

### Table for mean and standard deviation of "Excellent" responses in NY

``` r
brfss_data %>%
  group_by(year) %>% 
  filter(year == 2002 | year == 2006 | year == 2010) %>% 
  spread(key = response, value = data_value) %>% 
  janitor::clean_names() %>% 
  filter(locationabbr == "NY") %>% 
  summarize(mean_excellent = mean(excellent, na.rm = TRUE),
            sd_excellent = sd(excellent, na.rm = TRUE)) %>% 
  knitr::kable(digits = 1)
```

|  year|  mean\_excellent|  sd\_excellent|
|-----:|----------------:|--------------:|
|  2002|             24.0|            4.5|
|  2006|             22.5|            4.0|
|  2010|             22.7|            3.6|

Witin the state of New York, 2002 has the highest average of 24% for excellent responses, and a standard deviation of 4.5. Year 2006 has an average of 22.5% and standard deviation of 4.0. Year 2010 has an average of 22.7% and standard deviation of 3.6.

### Plot for distribution of each response category across states

``` r
brfss_data %>% 
  group_by(year, locationabbr, response) %>%
  summarize(mean_response = mean(data_value, na.rm = TRUE)) %>% 
  ggplot(aes(x = year, y = mean_response)) +
    geom_violin() +
    facet_grid(. ~ response) 
```

<img src="p8105_hw3_qg2155_files/figure-markdown_github/five plots-1.png" width="90%" />

Across all states and years, the response category of "Good" seems to have the highest average, followed by "Excellent", "Fair", and "Poor". Excellent seems to have the biggest range out of them all.

Problem 2
---------

### Load and clean dataset

``` r
data("instacart")
```

``` r
instacart_data = instacart %>% 
  janitor::clean_names() 
```

``` r
instacart_data %>% 
summarize(n_aisles = n_distinct(aisle_id))
```

    ## # A tibble: 1 x 1
    ##   n_aisles
    ##      <int>
    ## 1      134

There are 134 aisles.
